name: CI/CD Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: cicd-project
  BUCKET_NAME: cicd-bucket
  CODE_DEPLOY_APP_NAME: cicd-test
  DEPLOYMENT_GROUP_NAME: cicd-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Grant execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Build project
      run: ./gradlew build

    - name: Make Zip File
      run: zip -qq -r app.zip .
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 cp app.zip s3://${{ env.BUCKET_NAME }}/app.zip

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ env.BUCKET_NAME }},key=app.zip,bundleType=zip

          --deployment-group-name YourDeploymentGroupName \
          --s3-location bucket=your-s3-bucket-name,key=app.zip,bundleType=zip
